### ISSUE TITLE
Code from recently-uploaded tutorials do not work

### ISSUE THREAD

**Issue by annaritz** [FlickerSoul/Graphery#107]
**Describe the bug**
There are two new tutorials: 103-2 (which previously had an anchor but was not published) and 104-1.  These tutorials have code that works on graphs in the graph playground.  However, when they are loaded as tutorials, the code is not executed. No popup (error or otherwise) occurs.  
- When I click "run code in the cloud" nothing happens.
- When I click "run code locally", the page hangs.  Nothing is printed to the console. 

**To Reproduce**
1. Go to one of the tutorials ([here's a link to 103-2](https://graphery.reedcompbio.org/tutorial/en-us/shortest-paths-2))
2. Try clicking run from the cloud or run locally.

To see that the code actually works:
1. copy the code from the tutorial above.
2. Go to [the tutorial graph](https://graphery.reedcompbio.org/graph/en-us/tutorial-graph-1)
3. Copy the code in this editor.
4. Click run in the cloud or run locally; code will successfully execute.

**Comment by FlickerSoul** [comment]
Ok, this is a weird one. Turns out if the code won't run without default results loaded from the admin panel. I executed the code and uploaded the default results to the database and now it works fine. I will look into the code.
