### ISSUE TITLE
Language choice dropdown has display glitch 

### ISSUE THREAD

**Issue by FlickerSoul** [FlickerSoul/Graphery#109]
**Describe the bug**
The dropdown container will collapse if the language code of the current language is shorter than others. 

**To Reproduce**
* Clone the latest commit on fixes branch and build the frontend. 
* Click on the language choice button on the top right of the screen 
* Choose the language with a shorter language code 
* You should be able to see that the dropdown menu collapsed. 

**Expected behavior**
The shape of the dropdown menu should stay the same no matter what code you choose. 

**Screenshots**

https://user-images.githubusercontent.com/13360148/103452014-d3a07d00-4c7f-11eb-857e-22b5d5ebd859.mov

**Desktop (please complete the following information):**
* macOS Edge 87.0.664.66

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jukrb0x** [comment]
fixed in b08c734, issue closed.

**Comment by jukrb0x** [comment]
wait for production, re-open the issue.
