### ISSUE TITLE
Authors of translated tutorials are not listed

### ISSUE THREAD

**Issue by annaritz** [FlickerSoul/Graphery#143]
**Describe the bug**
In tutorial 001-1, when switching to Spanish, the author remains Larry only.  Gabe is included as an author in the control panel. 

**Expected behavior**
Ideally, authors + translators should be listed for each translated tutorial. (e.g., Larry is the sole author in English & Chinese, and Larry & Gabe are authors for the Spanish version.

**Comment by FlickerSoul** [comment]
Does the problem happen on the tutorial page only? I can see the metadata is not updated on that page after switching language. But reloading the page works. I can issue a quick fix now.
