### ISSUE TITLE
how do users know they must run in the cloud or locally first?

### ISSUE THREAD

**Issue by annaritz** [FlickerSoul/Graphery#81]
**Is your feature request related to a problem? Please describe.**
When a user is shown code, the first thing they must do is run either in the cloud or locally. It's not clear which buttons these are and that you cannot do anything until that happens.

**Describe the solution you'd like**
The user should be directed to these buttons at first glance.

**Describe alternatives you've considered**
These buttons should be highlighted (in color? popup that says "start here"? comment at the top of every file w/ instructions)

**Comment by FlickerSoul** [comment]
The pre-built results are provided to users when they load the page. Unless they make modifications to the code and want to see changes, they don't need the running on the cloud/local button. Am I misunderstanding anything?

**Comment by FlickerSoul** [comment]
I do think I need clear guidance for the user interface. But I think tutorial 0 and the extra tooltips will do the job. We will see.

**Comment by FlickerSoul** [comment]
A red accent color will be added to the next button if the execution step is at `1` in the next version.
