### ISSUE TITLE
"Play With It" buttons are not obviously buttons

### ISSUE THREAD

**Issue by annaritz** [FlickerSoul/Graphery#90]
**Is your improvement request related to a problem? Please describe.**
The "PLAY WITH IT" text at the bottom of graphs are actually buttons; this is not apparent.  

**Describe the solution you'd like**
Can we make them buttons (or at least enclose them?)

**Comment by annaritz** [comment]
Same goes for the "Read More" buttons on the tutorial page.

**Comment by FlickerSoul** [comment]
We tried to add shadows under the button but it turned out to be a bit overwhelming along with other shadows. My suggestion is to tweak the font size a bit and maybe also make it bolder. Jabriel @jukrb0x will follow up on this.

**Comment by jukrb0x** [comment]
fix in 96f3ac962c1c358eba5fdb1ec1cc22b650af3994

![image](https://user-images.githubusercontent.com/15688641/105414702-c8cf7b80-5c72-11eb-846e-716ddf01a04b.png)

- ignore the rank id background with yellow for this commit
- the button is outlined with primary color

more user-friendly design for article card will be discussed
