### ISSUE TITLE
Hovering over nodes and edges gives uninformative popup

### ISSUE THREAD

**Issue by annaritz** [FlickerSoul/Graphery#92]
**Is your improvement request related to a problem? Please describe.**
When you hover over nodes or edges in a graph, all popups are "Test Content 0".
![Screen Shot 2020-12-30 at 10 55 29 AM](https://user-images.githubusercontent.com/1457970/103374955-abe9c300-4a8d-11eb-8e74-f42c9dcd1012.png)
![Screen Shot 2020-12-30 at 10 55 35 AM](https://user-images.githubusercontent.com/1457970/103374956-adb38680-4a8d-11eb-9eef-2a79b42942a3.png)

**Describe the solution you'd like**
Either add node LABELS (what's displayed) and IDs (the numeric identifier, if there is one), and annotated edges by their incident nodes, OR remove this popup functionality.

**Comment by FlickerSoul** [comment]
My initial envision is that we can put properties of nodes and edges on the popup, like edge weight, or the accumulated distance during the computation of the shortest path algorithm. I will fix that later next week. This is related to some changes I am going to make to the graph API, which will be discussed in a new issue.

**Comment by FlickerSoul** [comment]
This is related to #69. Items in variable list should have the same design. @jukrb0x you should add your proposals and comments here.

**Comment by FlickerSoul** [comment]
The current API can't support informative popups. I put the query id to the tooltips so that users can use the id provided to get specific nodes or edges. 

I think the expected behavior has to wait for the next version.

**Comment by FlickerSoul** [comment]
I'll open another issue and a new RFC for this.
