### ISSUE TITLE
"Open Workspace" button is not implemented

### ISSUE THREAD

**Issue by annaritz** [FlickerSoul/Graphery#93]
**Describe the bug**
When you click the "Open Workspace" button, you get a "Not Yet Implemented" error.  It is not clear to me what a workspace is designed to be. I would suggest removing this button for the first release.

![Screen Shot 2020-12-30 at 11 01 01 AM](https://user-images.githubusercontent.com/1457970/103375230-8315fd80-4a8e-11eb-8671-dca5726815bb.png)

**Error**

![Screen Shot 2020-12-30 at 10 59 11 AM](https://user-images.githubusercontent.com/1457970/103375233-84472a80-4a8e-11eb-95a0-a340c66708a0.png)

**Desktop (please complete the following information):**
Chrome on  Mac OS Catalina

**Comment by FlickerSoul** [comment]
Good point. I will remove that along with the play button later today.
