### ISSUE TITLE
The lock/unlock hover text is ambiguous

### ISSUE THREAD

**Issue by annaritz** [FlickerSoul/Graphery#96]
**Is your improvement request related to a problem? Please describe.**
When you hover over the lock/unlock button, it says to go to settings to change editing permissions. This is kind of unclear.

![Screen Shot 2020-12-30 at 11 10 00 AM](https://user-images.githubusercontent.com/1457970/103375808-eb191380-4a8f-11eb-8e54-e252c43486a2.png)

**Describe the solution you'd like**
Some quick suggestions:
- Can there be a link to the settings page in the hover? 
- Alternatively, if someone clicks the button, can they be redirected to the settings page?  
- Finally, the text could be rephrased (though it's wordy). "Edit the code. Go to Settings to enable this feature."

**Comment by FlickerSoul** [comment]
I would suggest we can change the button to a toggle so that users can change the edit setting directly. Could you remind me why we should put the toggle to the settings page? 

Do you jukrb0x have any suggestions?

**Comment by annaritz** [comment]
I don't think we need it on the settings page, but I like that it's there.
My point is it should default to NOT being editable (which is currently
what it's doing so that's good). Right now it doesn't make sense to be in
the button panel when you can never actually click it.

Can you make it so you click the lock on any page with code to change the
setting (which is still global)?  Then the lock/unlock feature would be
intuitive, I think.

Anna

**Comment by FlickerSoul** [comment]
Got ya!

**Comment by FlickerSoul** [comment]
fixed in 9423a6040bb8e33eacab374a8cf82a50153c0954
