### ISSUE TITLE
Email Me email should go to an alias

### ISSUE THREAD

**Issue by annaritz** [FlickerSoul/Graphery#97]
**Is your improvement request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by annaritz** [comment]
Sorry, cat stepped on the keyboard! Hah.

The "Email Me" emails should be "Email Graphery Developers".  This will allow us to add people to help monitor questions, others may leave the project, and email addresses may change (e.g. post-college).

I will make an alias (graphery@reed.edu) and add myself and Larry as recipients.  I will comment here once that is done.

**Comment by FlickerSoul** [comment]
Ok great!

**Comment by annaritz** [comment]
graphery@groups.reed.edu is ready to use. @FlickerSoul and I will receive emails to this address. You can close this issue when the "Email Us" button is updated to use this email.

**Comment by FlickerSoul** [comment]
Sweet!
